### PR TITLE
fix: markdown.util.etree is deprecated

### PR DESCRIPTION
**Pull request by Mara-Li**
Using Markdown last version (3.4.1) the serve getting an error because of the deprecation of markdown.util.etree.

### CODE REVIEW

**Comment by emign** [comment]
Relevant:
https://github.com/neurobin/mdx_wikilink_plus/issues

**Comment by neurobin** [comment]
Several issues:

1. `setup.py`: You have changed the code around version which results in version mismatch (in one place 1.4.1, and in another 1.4.3) due to hard coding the version in setup.py. Please do not do so. Please do not change anything in setup.py file especially the author and related info. You shouldn't need to change anything here.
2. `setup.cfg`: Please remove this file.

**Comment by Mara-Li** [comment]
> Several issues:
> 
> 1. `setup.py`: You have changed the code around version which results in version mismatch (in one place 1.4.1, and in another 1.4.3) due to hard coding the version in setup.py. Please do not do so. Please do not change anything in setup.py file especially the author and related info. You shouldn't need to change anything here.
> 2. `setup.cfg`: Please remove this file.

Sorry for that, as I had 4 plugins related to mdx, i needed to create a little fork and a package in waiting for the PR! 
I will clean the repo :)

**Comment by Mara-Li** [comment]
Could you please check if everything is okay now ? :)

**Review by neurobin — APPROVED** [review]
Looks good.

**Pull request merged**
